### ISSUE TITLE
HOW to do quantitative analysis

### ISSUE THREAD

**Issue by hmyh1202** [shizhuoxing/Full-Length-RNA-Analysis-Best-Practice#2]
Hi ,
   AS in your design, you had add UMI tags in your library, so how to do quantitative analysis on isform level ?
The Best !

**Comment by shizhuoxing** [comment]
hi, quantifying isoform level expression is just under development.
the main process i can give here you can refer to: 
1, first, map all isoforms to genome, using minimap2 now is popular;
2, then collapse isoforms by genome loci, such as using cDNA_cupcake; 
3, base on collapse result, you can have script on you own to process the count result by UMI in each group (uniq isoform).

more discussion is welcome.

**Comment by hmyh1202** [comment]
Sorry, can the transcripts with the same UMI removed after ccs process ? In your step 3 above, process the count result by UMI in each group, the was the step used for get quantity value for each gene ?

Than you.

**Comment by shizhuoxing** [comment]
Generally, you can't removed sam UMI after CCS process, because difference isoforms may have sam UMI. I have posted above in step3, the UMI count value just representative of isoforms level expression, if you want to get the gene level expression value, here you may can have additional Step 4:
1...
2...
3...
4. compare each group gff to reference gff using gffcompare, than parse the *.tmap file and sum it up each gene expression value base on Step 3.

**Comment by hmyh1202** [comment]
Sorry, again , In your STEP 3 "base on collapse result, you can have script on you own to process the count result by UMI in each group", why not just use collapse transcript counts number as the expression count ? In 10X genomics technology, the umi used to identify the PCR`s transcripts.

**Comment by shizhuoxing** [comment]
Step 3 i have writed that "...count result by UMI in each group..."
